dist: trusty
sudo: required
language: bash
before_install:
- curl https://raw.githubusercontent.com/express42/otus-homeworks/2018-11/run.sh |
  bash
notifications:
  slack:
    rooms:
      secure: WFUj2lBdGdgwq42bhbq5pJB7ICUlXF6yjOMCTJD0bFM5xOIuj+B1EwAPKkCAffCoxDA/OIL0JVFZ1DuGZhii8Hoi4V7o7LDFmtMPMJI2ZcPBFVOhYlPLy2JytmxEpVdrAkiDX7POSxZFPtq7Q6hDPJ1Xx7dR7GeyMinj2Z7D40dpa55bdEcruKm/3qczfLp1BVeHOscy8cwf4gi+SvVGKmDHHmrM3Va7hqQOU+XLnStKAgWKo7sqxj+S5rhlpJ7oJQK/Uaf5dkFmca6CaLFlZNxV7roNSsLRNnSfeQ2epSYMf3mq2n1ng0OU81bRlGTRlTs40EwJBqQB18DiIKRnGflhTULo9/59mjmIuPil+EZqCtD7wiuhu+5oXj2HnIIyn7Ubk0McqY27I07gAttUsPTgeuAqud1NWiP1Dus0Qxdf6BGhNypuoTv0+bd5fFT8TJc5DNwH6eHIFViCzSO7guSuwIY9EXgA8/lq0WHDAxdQB3aSEAleEZUMNwZdYkXgzShCHalX8T8TBapQAxTjrW5VTCkN44FvDxvwTHyjCJOG9WMzVQnNMlkZY0PW9Ht6WVcRc+zDPOd+A+QOOT4u7s2kBhEn+gAenDv3yL1q7eRu31sDtWQw3Bb7eOTfVbL2E4RTZ/kp+zuHzJbhUSNilVCoUPV2kJMi7h/vyFDlJvI=
